// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe8zm_e8stv-nwPCKAceJ09KJKCF1b4OM',
    appId: '1:845516856992:web:15f4a2c92ed6e5ee20b3c5',
    messagingSenderId: '845516856992',
    projectId: 'kuberwakatende-notes-project',
    authDomain: 'kuberwakatende-notes-project.firebaseapp.com',
    storageBucket: 'kuberwakatende-notes-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzlzQFIqiao-xH4-grWLPgCbBx1IU_x0',
    appId: '1:845516856992:android:1c1c68973713f40720b3c5',
    messagingSenderId: '845516856992',
    projectId: 'kuberwakatende-notes-project',
    storageBucket: 'kuberwakatende-notes-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHAIxXva6ipZHBkYAtitple1E0lzzGOk',
    appId: '1:845516856992:ios:ccaea2be62bc56e920b3c5',
    messagingSenderId: '845516856992',
    projectId: 'kuberwakatende-notes-project',
    storageBucket: 'kuberwakatende-notes-project.appspot.com',
    iosBundleId: 'com.practice.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHAIxXva6ipZHBkYAtitple1E0lzzGOk',
    appId: '1:845516856992:ios:2eab10ed2a83e22d20b3c5',
    messagingSenderId: '845516856992',
    projectId: 'kuberwakatende-notes-project',
    storageBucket: 'kuberwakatende-notes-project.appspot.com',
    iosBundleId: 'com.practice.notes.RunnerTests',
  );
}
